# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: iter_dataset.yaml
  - model: backbone_generative.yaml
  - callbacks: default_callbacks.yaml
  - feature_dict: feature_dict_kin_massless.yaml
  - logger: many_loggers.yaml # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: example_experiment_generative.yaml

  # config for hyperparameter optimization
  - hparams_search: null

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default.yaml

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# task name, determines output directory path
task_name: "train"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
# appending lists from command line is currently not supported :(
# https://github.com/facebookresearch/hydra/issues/1547
tags: ["dev"]

# set False to skip model training
train: true

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: true
test_only_on_rank_zero: true

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 12345

# if this is specified (with a path in the command line), this ckpt will be loaded
# and the corresponding model will be evaluated. Note that it will also load the
# config.yaml in that directory, so any overrides need to be specified for that format.
ckpt_path_for_evaluation: null

# this option is used if you run on a cluster with very limited training time per job
# --> then you can specify the output dir like this, and the training will continue
# from the last checkpoint in the output dir (if it exists)
output_dir_resub: null

# this is only used for bookkeeping. It doesn't do anything with the code itself, but
# can be used with the `dataset_size_to_dataset_kwargs` function from gabbro.utils.submit_tools
dataset_size_id: null
